### ISSUE TITLE
character encoding

### ISSUE THREAD

**Issue by 56miles** [tflanagan/node-quickbase#16]
Hi - I'm guessing this is an issue with quickbase and not with this module, but I thought I would ask here anyway! I'm having issues updating quickbase fields with non-Western characters. When I update a field with this module and then view it in quickbase (after changing my browser's character encoding settings to UTF-8), some of the characters display correctly, but others show as question marks. I tried changing the module's encoding setting to UTF-8, but this actually made it worse (now ALL the non-Western characters display incorrectly). Is there another charset I can use that will fix this? Or is this a larger issue with quickbase (I know they don't really support other languages). Thanks!

**Comment by tflanagan** [comment]
Hey,

Quick Base hasn't had a stellar track record with this. The company I work for, Data Collaborative, has written an article on how to deal with it in the browser - https://datacollaborative.com/quickbase-applications-international-text-encoding. But it sounds like you've solved that issue.

Any chance you can post some code so I can try to reproduce?

Thanks,

**Comment by 56miles** [comment]
Yeah - I get how to change the browser encoding, and I see if I download a CSV report from quickbase then I can open it in excel as a UTF-8 encoded file by using File >> Import, and I found that if I manually update a quickbase record in the browser then the non-Western characters will save correctly (if my browser is set to UTF-8), BUT when I try to send the non-Western characters through the API, it doesn't work.

I'm just adding a new record, like this. All the fields I'm adding are in Western characters except for first and last name, which are sometimes in non-Western.

quickbase.api("API_AddRecord", {
  dbid: studentsDbId,
  fields: studentFields
}).then((result) => {
  console.log(result);
})

As an example, if I send this first name: マイケル and this last name: ジャクソン this is what goes through to quickbase: 

firstname: ã??ã?¤ã?±ã?«
lastname: ã?¸ã?£ã?¯ã?½ã?³

And when I change my browser's encoding to UTF-8, I get this:

firstname: �??�?��?��?�
lastname: �?��?��?��?��?�

It's weird - for some of the names that are coming in, a few characters do convert correctly when I change my browser to UTF-8, but none of them fully convert - and some, like this one, don't convert  at all (just question marks).

**Comment by tflanagan** [comment]
Thanks for the information and sample characters. I'll play around and let you know what I find.

**Comment by 56miles** [comment]
Hey! Just wondering if you've been able to take a look at this?
