### ISSUE TITLE
XML Parsing RTF Fields

### ISSUE THREAD

**Issue by jmitchell922** [tflanagan/node-quickbase#18]
With the new Rich Text Fields, XML Parsing is broken. QuickBase sends the XML response with `<BR/>` not escaped so when xml2js parses it, you have output like this: 

{ _: 'Some text',
  BR: [ '', ''] }

The BR tags need to be escaped.

**Comment by tflanagan** [comment]
Hey, thanks for the feedback!

I'm well aware of Quick Base's &lt;br /&gt; bug... I opened a support cased quite some time ago (7/29/2015 at 5:19 pm). There is also a "\r\n" bug when an xml array is "empty".

Support Case 480141 - They haven't made any progress on the support case, last I heard it is "open". Nearing 3 years later, so I highly doubt it's going to get fixed.

**Comment by jmitchell922** [comment]
Oh. Yeah this is a bit of a problem. It breaks the XML parsing of xml2js. I submitted a pull request with a fix I implemented for my purposes. The `<BR/>` tag isn't needed because it also sends a newline as well, so added a xml node parse function to strip it.

**Comment by brianppoole** [comment]
Just thinking out loud here. Is it possible to just strip out the "<br/>"
from the response string?

**Comment by jmitchell922** [comment]
Yes, but this has to be done before the XML is parsed into JS, xml2js is what causes the problem. I added a a xml node parser to strip the `<br/>` tag in the pull request I submitted.

**Comment by tflanagan** [comment]
xml2js isn't the issue, it is creating json we don't like, but `<br />` is valid xml. Quick Base is the real culprit.

@jmitchell922 could you give me a test scenario that reproduces your issue? Field type, value and the api call you're using?

**Comment by jmitchell922** [comment]
Sure: 

Field type: Rich Text Field
Value: Anything that spans multiple lines.
API_DoQuery

Result without stripping `<BR/>`:

{ _: 'Data from field',
     BR: [ '', '', '', '', '', '' ] },

**Comment by jmitchell922** [comment]
An alternative to stripping it, if you want to leave it in is to replace it with &lt;br&gt;

**Comment by brianppoole** [comment]
Ah, sorry I was suggesting to do the string replace in the library.

Basically, right after the response comes back from QuickBase, sanitize the string. Either remove it or replace it with valid XML.

**Comment by jmitchell922** [comment]
Oh, yeah I've done this. I suppose I could build the module and include it in my project manually with this change. I have to push this to a cloud environment as well, so when I run NPM install there the changes I've made do not persist.

**Comment by jmitchell922** [comment]
Is there any chance of this being implemented?

**Comment by tflanagan** [comment]
Yea, just a bit busy right now. I'll get to it shortly

**Comment by jmitchell922** [comment]
We came up with a way to overwrite it without modifying the NPM package:

`var parseStringActual = xml2js.parseString;

xml2js.parseString = function (str, a, b) {
    str = str.replace(/<[Bb][Rr]\/>/g, '');

    parseStringActual(str, a, b);
}`

**Comment by obe711** [comment]
I'm excited to see that.

**Comment by AdamBethke** [comment]
@obe711 - finally got it approved to migrate from a private repo to a public one: https://abethke.gitlab.io/qbpy/

**Comment by tflanagan** [comment]
Closing.

take a look at v3, this version targets the new json based api
