### ISSUE TITLE
`API_ImportFromCSV` will fail if sending a JSON.stringify'ed payload

### ISSUE THREAD

**Issue by benedictchen** [tflanagan/node-quickbase#21]
The following payload will fail, but it shouldn't:
```
JSON.stringify({x:{a:1,b:2,c: [1,2,3,4,5,6]}})
```

**Comment by tflanagan** [comment]
Hi @benedictchen,

This library really only serves as a base level interface with Quick Base. It covers the HTTP request/response handling and XML to JSON conversation and that's about it. I purposely did not try to intervene with data handling in this library.

I've built additional layers that handle dealing with Quick Base's API quirks. What you're probably running into is CSV formatting issues.

Take a look at these libraries to help dealing with Quick Base's API:
* [QBField](https://github.com/tflanagan/node-qb-field)
* [QBRecord](https://github.com/tflanagan/node-qb-record)
* [QBTable](https://github.com/tflanagan/node-qb-table)

If you believe this is more than a formatting issue with your payload, then please re-open this issue and provide a test case (copy/paste for me would be wonderful) so I can further investigate
