### ISSUE TITLE
Please include how to use UTF-8 encoding in the docs

### ISSUE THREAD

**Issue by benedictchen** [tflanagan/node-quickbase#22]
I tried to use UTF-8 encoding, but didn't seem to work.  Please include example usage in docs if possible.

**Comment by tflanagan** [comment]
Quick Base has an ongoing issue with supporting UTF-8 with their API.

Here is a snippet from my conversation with their support team:

"...while UTF-8 should support Russian as indicated in our research; The Quick Base platform has not made it a priority to ensure that we support international characters with UTF-8. That in turn requires users/QSPs to find workarounds to just get a close as possible to working."

Unfortunately, there isn't much I can do to help as it is an issue with the platform, not this library.

However, to answer your question, all you need to do is this to enable UTF-8:

```js
const QuickBase = require('quickbase');

const quickbase = new QuickBase({
  flags: {
    encoding: 'UTF-8'
  }
})
```
