### ISSUE TITLE
QuickBase Dev Tools : Records ||  .toJson([fidsToConvrert]) 

### ISSUE THREAD

**Issue by bowencl5157** [tflanagan/node-quickbase#27]
Please see the below example. 

The example does not show where the project variable is declared or what it is intended to represent. 

Should there be a load function? 
Is there a set DBName? 

Not sure what is required to make this work.

======================================================
.toJson([fidsToConvrert]) 
----------------------------

project.set('projectName', 'Some Example Project');
project.set('completed', false);
project.set('finishDate', moment(1587355200000));
project.set('elapsedTime', moment.duration(10800000));
project.set('$tableRow', $('.some-tr-row'));

task.set('taskName', 'Some Task');

project.set('tasks', [
  task
]);

project.toJson();

**Comment by tflanagan** [comment]
Hi @bowencl5157,

This is in reference to a different library, https://github.com/tflanagan/node-qb-record, which sits on top of this library.

Anyway, here is how you could use that method from start to finish:

```js
const QuickBase = require('quickbase');

const qb = new QuickBase({
    realm: '',
    userToken: ''
});

const table = new QBTable({
    dbid: '',
    fids: {
        name: 6
    }
});

table.load().each((record) => {
    console.log(record.toJson());
}).catch((err) => {
    console.error(err);
});
```

**Comment by bowencl5157** [comment]
Thanks Tristian

Your api has helped me a great deal.
