### ISSUE TITLE
bluebird inclusion leads to large memory usage increase

### ISSUE THREAD

**Issue by BryceBarbara** [tflanagan/node-quickbase#29]
While chasing down some memory usages in an internal system we've got, I came across the quickbase library holding onto a ton of data that was no longer relevant. It turns out to be some sort of issue with bluebird that I didn't feel like tracking down.  
[Screenshot of the memory usage for the curious](https://user-images.githubusercontent.com/24460210/88223062-bd47bd00-cc1b-11ea-9605-9a10f25d3b4f.png)

My question is why is bluebird needed in the first place when Promise already exists? If you look at the screenshot, the first two snapshots are with bluebird included and the last two are with the bluebird inclusion commented out. Memory usage drops by almost 50%.

If bluebird is needed for some specific reason, could we get a version of the quickbase library to import that doesn't include that extra library?

**Comment by BryceBarbara** [comment]
Oops, looks like I'm using a way out of date version! Please disregard! Thanks for the great library :)

**Comment by tflanagan** [comment]
Hey @BryceBarbara, thanks for the report.

You aren't using an out of date version, v2 targets the XML API, v3 targets Quick Base's new API.

Yes, when this library was first developed, `Promise` wasn't as globally supported as it is now in browsers and this library targets both Node.js and browsers.

Unfortunately, the `Promise` API that `bluebird` provides has many more methods than the native `Promise` object, so removing `bluebird` would be a `major` [version change](https://semver.org/) for v2 as the promises returned by the library wouldn't have the same methods available.

I'd first recommend trying v3 of this library which targets the new RESTful API Quick Base took out of beta over Empower2020.

You can use both v2 and v3 at the same time (requires npm >= 6.9.0)

`$ npm install --save quickbase-old@npm:quickbase@2 quickbase-new@npm:quickbase@3`

```js
const QuickBaseOld = require('quickbase-old');
const { QuickBaseNew } = require('quickbase-new');
```

If that's not possible, I understand the desire to remove `bluebird`, it has crossed my mind a number of times as well, but I'll have to come up with some versioning solution to provide that.

Let me know if v3 resolves the issue for you.

**Comment by BryceBarbara** [comment]
I'm currently in the process of trying to migrate to v3 but I've noticed that CSV import is missing which means I'll need to use v2 and v3 at the same time. I had no idea that was even possible with `npm` so I really appreciate the pointer!

As for the promises and breaking changes, you _could_ introduce a new file that is manually imported instead of the default. Something like this:
```js
const QuickBase = require('quickbase/quickbase.native-promises');
```
That would allow users to update without risking any breaking changes while still allowing other users (heh, only me) to import the one that doesn't have bluebird.

**Comment by tflanagan** [comment]
@BryceBarbara That's an interesting concept. I'll take a look at it.

For API_ImportFromCSV, you'll want to use upsertRecords operation. upsertRecords is a combination of API_AddRecord, API_EditRecord, and API_ImportFromCSV: https://developer.quickbase.com/operation/upsert

**Comment by BryceBarbara** [comment]
I ended up migrating everything over only to realize that v3 still uses bluebird via generic-throttle 😭

**Comment by tflanagan** [comment]
@BryceBarbara 😰yikes.. forgot about that one.

I'll work on finding a path to replace it.

**Comment by tflanagan** [comment]
@BryceBarbara bluebird removal has been finalized with the release of v4 - 95ca006

**Comment by BryceBarbara** [comment]
It's... it's beautiful. Thank you so much for helping me with this! 

It's been a journey squashing memory usage in a project that spawns a ton of sub-processes. This was one of the last big culprits that wasn't directly caused by something in my code base so I'm glad it's done for now
