### ISSUE TITLE
Unable to set fmt to unstructured

### ISSUE THREAD

**Issue by 3IMOH** [tflanagan/node-quickbase#3]
Hello-

I am trying to get my results in a non-structured format. I attempted to override the default by setting fmt = '' but this does not seem to be working:

var qb = new quickbase({
	realm: settings.qbRealm,
	appToken: settings.qbAppToken,
	flags: {
		fmt: '' 
	}	
});

Is there another way to remove this flag?

thanks,
Howie

**Comment by tflanagan** [comment]
```
var qb = new quickbase({
  realm: '',
  appToken: '',
  flags: {
    fmt: false
  }
});

**Comment by 3IMOH** [comment]
Thanks Tristan-
Upon further testing, it turns out that it was working...my issue was that I was not interpreting the result properly because of the change in format when using unstructured. Sorry for the bother and thanks for your work on this.
