### ISSUE TITLE
appToken Error

### ISSUE THREAD

**Issue by jtorrence1** [tflanagan/node-quickbase#30]
The Initialization documentation says that appToken parameter is not required, but whenever initiate with only a userToken and make an API call I get an error like:
"Invalid Application Token: An Application Token must be supplied."

**Comment by tflanagan** [comment]
Quick Base's documentation is incomplete.

Please refer to the README for how to include an app token (it is commented out).

```
const quickbase = new QuickBase({
    realm: 'demo',
    appToken: '<app token>'
});
```

This is only required for "client-side" work, where you want to consume to currently logged in users session. Keep in mind you must call `getTempToken` first.

**Comment by jtorrence1** [comment]
Sorry,

I just meant that Quick Base doesn't actually require an AppToken for the "API_GetRoleInfo" call to succeed. Here's a cURL command that illustrates what I mean.
```bash
curl --location --request POST 'https://[example].quickbase.com/db/[dbid]?act=API_GetRoleInfo' \
--header 'Content-Type: application/xml' \
--data-raw '<qdbapi>
    <usertoken>[usertoken]</usertoken>
</qdbapi>'
```

**Comment by jtorrence1** [comment]
I think I see what you mean. Whenever you provide a cookie, Quick Base requires an App Token. That's a weird behavoir.

**Comment by tflanagan** [comment]
Hey @jtorrence1,

Correct, when you are using a user token you do not need an app token. However, if you are using a ticket, you must supply an app token if the Quick Base application is setup to require it.

Glad you were able to figure it out on your own.
