### ISSUE TITLE
Updating a record

### ISSUE THREAD

**Issue by mmeierhoefer** [tflanagan/node-quickbase#38]
So this should be an easy one - I just can't figure it out.  I'm migrating from version 2.something to 4.2.2 and I can't find in the documentation how to update a record.  quickbase.upsertRecords seems like a possibility - but I don't see a place for a record ID.  Is it like mongoDb/mongoose where you run a query, then something like 'record.set('fieldID', 'value')', then something like 'record.save()'?  Or am I just not seeing the right funtion/method?  Thanks.

**Comment by tflanagan** [comment]
In `quickbase` you'll be using `upsertRecords()`, you can find the documentation from Quickbase [here](https://developer.quickbase.com/operation/upsert).

Essentially, it will look like this:

```js
await qb.upsertRecords({
	tableId: 'xxxxxxxx',
	mergeFieldId: 3,
	data: [{
		'3': {
			value: 42
		},
		'6': {
			value: 'Some Field'
		}
	}]
});
```

The `mergeFieldId` is what makes it update a record.

You reference a `.save()` method, but I think you're thinking of `qb-record` and `qb-table`. Those are abstraction layers that sit on top of this library.

**Comment by mmeierhoefer** [comment]
So `mergeFieldId` will be the recordID of record I need to update?  Or is it the fieldID of the default index field of the table?  If it's the latter - I still can't work out how it knows which record to update.

**Comment by tflanagan** [comment]
In this case, yes, `mergeFieldId` would be the field id of the Primary Key, most likely [Record ID#], which is field id 3.

It knows which record to update by you supplying the Record ID# of each record you which to update in the record array. See my earlier example. You would replace `42` which whatever Record ID# you want to edit.

To edit multiple records, use multiple objects:

```js
await quickbase.upsertRecords({
	tableId: 'xxxxxxxx',
	mergeFieldId: 3,
	data: [{
		'3': {
			value: 42
		},
		'6': {
			value: 'Some Field'
		}
	}, {
		'3': {
			value: 20
		},
		'6': {
			value: 'Some Other Record'
		}
	}]
});
```
