### ISSUE TITLE
Using Node-Quickbase with angular

### ISSUE THREAD

**Issue by taylorhardy** [tflanagan/node-quickbase#4]
Could you explain how this module would work in a stack project using express and angular? Is it, in its current form, capable of doing this? Disregarding the issue of cross domain access.

**Comment by tflanagan** [comment]
I'm honestly not familiar enough with Angularjs. It sounds like you could create a service to bridge the gap between this API and your front-end.

More information on what you are trying to do would help.

**Comment by taylorhardy** [comment]
currently we are using the quickbase HTTP API within the quickbase platoform and using angular to manipulate the data. What i would like to do is to be able to use as much of that code as possible from that project because the point of using this would be to be able to not have to use their platform to edit code because its a hassle.

**Comment by tflanagan** [comment]
The Native JavaScript API provided by Intuit is by no means compatible with this API.

It would be a full rewrite in terms of function execution, but the parameters, (fields, clist, slist, options, etc) all behave the same, so your data compilation code can remain the same, but the code that will call this API would have to change.

Example:
Native: QB.DoQuery = function ( dbid, query, clist, slist, options )
This API: qb.api('DoQuery', {dbid: 'dbid', query: 'query', clist: 'clist', slist: 'slist', options: 'options', udata: 'udata', etc etc})
