### ISSUE TITLE
deepmerge dependency

### ISSUE THREAD

**Issue by joelhickok** [tflanagan/node-quickbase#49]
`deepmerge` did not used to be a dependency the user needed to install, but now it is.  Just wondering if this is intentional?

**Comment by tflanagan** [comment]
Yes, this is intentional.

This package used to have an extension of the `Object` object that added an `extends` method. To replace this functionality and avoid manipulating a global object, I shifted over to using `deepmerge`.

Are you experiencing any problems or was this just a curiosity?

**Comment by joelhickok** [comment]
Just getting back to this now... no, no problems.  It was just a new change, and it's fairly uncommon to need a utility package installed first, but it's fine.  I am more used to this in the case of tools that build on other frameworks.  For example, sveltestrap needing both svelte installed first.  

You library is wonderful!  I use it constantly to save time repeatedly writing my own algorithms.

**Comment by tflanagan** [comment]
Thank you for that feedback, very happy to hear it! 

I was trying to avoid extending the `Object` prototype with my own methods (this is frowned on by the community) and deepmerge looked like a nice, simple, small package that did what I needed.
